In [2]:
import pandas as pd
pd.__version__

'1.2.4'

In [47]:
import numpy as np

In [33]:
df = pd.read_csv('housingdata.csv')

In [6]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [7]:
df.shape

(20640, 10)

In [16]:
df['total_rooms'].isna().all()

False

In [17]:
df['total_bedrooms'].isna().all()

False

In [18]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [34]:
# for houses located to near bay
df_nb = df[df['ocean_proximity'] == 'NEAR BAY']
df_nb['median_house_value'].mean()

259212.31179039303

In [35]:
df['total_bedrooms'].mean()

537.8705525375618

In [40]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean()).mean()

537.8705525375639

In [37]:
df_nb2 = df[df['ocean_proximity'] == 'NEAR BAY']
df_nb['median_house_value'].mean()

259212.31179039303

In [38]:
df['total_bedrooms'].mean()

537.8705525375639

In [41]:
isl_df = df[df['ocean_proximity'] == 'ISLAND']

In [44]:
isl_df2 = isl_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
isl_df2

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [49]:
isl_dfn = isl_df2.to_numpy()

In [51]:
matrix = np.dot(isl_dfn.T, isl_dfn)

In [ ]:
# Compute the inverse of XTX.
# Create an array y with values [950, 1300, 800, 1000, 1300].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the last element of w?

In [55]:
inv_matrix = np.linalg.inv(matrix)
inv_matrix

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [56]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [60]:
transp_x = isl_dfn.transpose()
transp_x

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [63]:
final_matrix = np.matmul(inv_matrix, transp_x)
final_matrix

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [64]:
super_final = np.matmul(final_matrix, y)
super_final

array([23.12330961, -1.48124183,  5.69922946])